import { test, expect } from '@playwright/test';

test('AI Planner accepts inputs and generates valid payload', async ({ page }) => {
  await page.goto('/planner');

  // Verify Planner layout
  await expect(page.getByRole('heading', { name: 'AI Budget Planner' })).toBeVisible();

  // Ensure Party mode is selectable
  await page.getByRole('button', { name: 'Party' }).click();

  // Input Data
  const peopleInput = page.locator('input[type="number"]').first();
  await peopleInput.fill('15');

  const budgetInput = page.locator('input[type="number"]').nth(1);
  await budgetInput.fill('75000');

  // Trigger AI
  const generateBtn = page.getByRole('button', { name: 'Generate Smart Plan' });
  await expect(generateBtn).toBeVisible();
  await generateBtn.click();

  // Await processing
  // Since Gemini API can take a few seconds, we bump timeout to 15s for this assertion
  await expect(page.getByText('AI Plan Generated! ✨')).toBeVisible({ timeout: 15000 });
  
  // Verify standard layout structures generated by AI mapping
  await expect(page.getByText('Suggested Allocation')).toBeVisible();
  await expect(page.getByText('AI Travel Tips')).toBeVisible();
});
